version: '3.4'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
#      - ./mysql:/var/lib/mysql

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379