idus:
  datasource:
    read-only:
      #      data-source-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: root
      password: root

    write:
      #data-source-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: root
      password: root