idus:
  datasource:
    read-only:
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: readonly
      password: readonly

    write:
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: write
      password: write