spring:
  profiles:

  redis:
    host: localhost
    port: 6379

  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    com.nubiform: DEBUG

mybatis:
  mapper-locations: classpath:/query/*.xml

# swagger-ui custom path
springdoc.swagger-ui.path: /swagger-ui.html

management:
  #endpoints.web.exposure.include: caches, health, metrics
  endpoints.web.exposure.include: '*'

idus:
  datasource:
    read-only:
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: readonly
      password: readonly

    write:
      jdbc-url: jdbc:mysql://localhost:3306/idus
      username: write
      password: write